"""add library_exercise_id to exercises

Revision ID: 032c4acbfc78
Revises: 3c7d36f2e4e7
Create Date: 2026-07-15 19:02:36.393689

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '032c4acbfc78'
down_revision = '3c7d36f2e4e7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('exercises', schema=None) as batch_op:
        batch_op.add_column(sa.Column('library_exercise_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_exercise_library', 'exercise_library', ['library_exercise_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('exercises', schema=None) as batch_op:
        batch_op.drop_constraint('fk_exercise_library', type_='foreignkey')
        batch_op.drop_column('library_exercise_id')

    # ### end Alembic commands ###
