"""Make trainer_id nullable

Revision ID: 03763b9c3229
Revises: 8fb973e79895
Create Date: 2026-06-16 00:12:58.376783

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '03763b9c3229'
down_revision = '8fb973e79895'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('clients', schema=None) as batch_op:
        batch_op.alter_column('trainer_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('clients', schema=None) as batch_op:
        batch_op.alter_column('trainer_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
