"""add exercise_library table

Revision ID: 3c7d36f2e4e7
Revises: 4e22c07d8b6d
Create Date: 2026-07-15 18:49:37.721570

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3c7d36f2e4e7'
down_revision = '4e22c07d8b6d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('exercise_library',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('external_id', sa.String(length=10), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('body_part', sa.String(length=100), nullable=False),
    sa.Column('target', sa.String(length=100), nullable=False),
    sa.Column('equipment', sa.String(length=100), nullable=False),
    sa.Column('secondary_muscles', sa.JSON(), nullable=True),
    sa.Column('instructions', sa.Text(), nullable=True),
    sa.Column('image_url', sa.String(length=500), nullable=True),
    sa.Column('gif_url', sa.String(length=500), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('exercise_library', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_exercise_library_external_id'), ['external_id'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('exercise_library', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_exercise_library_external_id'))

    op.drop_table('exercise_library')
    # ### end Alembic commands ###
