"""week_day added in ClientRoutine

Revision ID: 4325e72e2786
Revises: 61d7c949f6ae
Create Date: 2026-07-02 22:02:49.235047

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4325e72e2786'
down_revision = '61d7c949f6ae'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('client_routines', schema=None) as batch_op:
        batch_op.add_column(sa.Column('week_day', sa.String(length=120), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('client_routines', schema=None) as batch_op:
        batch_op.drop_column('week_day')

    # ### end Alembic commands ###
