"""Height optional temp

Revision ID: 61d7c949f6ae
Revises: b9042857a01d
Create Date: 2026-06-24 18:26:40.491025

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '61d7c949f6ae'
down_revision = 'b9042857a01d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('clients', schema=None) as batch_op:
        batch_op.alter_column('height',
               existing_type=sa.FLOAT(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('clients', schema=None) as batch_op:
        batch_op.alter_column('height',
               existing_type=sa.FLOAT(),
               nullable=False)

    # ### end Alembic commands ###
