"""add token_password_reset_expires_at to users

Revision ID: b2df46f58196
Revises: b11b0b0a4735
Create Date: 2026-07-22 15:05:25.249835

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b2df46f58196'
down_revision = 'b11b0b0a4735'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('token_password_reset_expires_at', sa.DateTime(timezone=True), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('token_password_reset_expires_at')

    # ### end Alembic commands ###
