"""Client Trainer Column Optional Refactor, and Trainer Specialty Column Added

Revision ID: bb53e996834e
Revises: fac515583f40
Create Date: 2026-06-17 01:53:35.293767

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bb53e996834e'
down_revision = 'fac515583f40'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trainers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('specialty', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trainers', schema=None) as batch_op:
        batch_op.drop_column('specialty')

    # ### end Alembic commands ###
