"""add indexes to exercise_library body_part target equipment

Revision ID: c2fdaeb85046
Revises: 032c4acbfc78
Create Date: 2026-07-15 19:34:54.530171

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c2fdaeb85046'
down_revision = '032c4acbfc78'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('exercise_library', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_exercise_library_body_part'), ['body_part'], unique=False)
        batch_op.create_index(batch_op.f('ix_exercise_library_equipment'), ['equipment'], unique=False)
        batch_op.create_index(batch_op.f('ix_exercise_library_target'), ['target'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('exercise_library', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_exercise_library_target'))
        batch_op.drop_index(batch_op.f('ix_exercise_library_equipment'))
        batch_op.drop_index(batch_op.f('ix_exercise_library_body_part'))

    # ### end Alembic commands ###
