"""routine_id optional exercise rework

Revision ID: c94abd54940b
Revises: 4325e72e2786
Create Date: 2026-07-05 14:54:54.321083

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c94abd54940b'
down_revision = '4325e72e2786'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('exercises', schema=None) as batch_op:
        batch_op.alter_column('routine_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('exercises', schema=None) as batch_op:
        batch_op.alter_column('routine_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
