"""Make height nullable

Revision ID: fac515583f40
Revises: 03763b9c3229
Create Date: 2026-06-16 00:14:38.461186

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fac515583f40'
down_revision = '03763b9c3229'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('clients', schema=None) as batch_op:
        batch_op.alter_column('height',
               existing_type=sa.FLOAT(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('clients', schema=None) as batch_op:
        batch_op.alter_column('height',
               existing_type=sa.FLOAT(),
               nullable=False)

    # ### end Alembic commands ###
